# Packs the project into one zip that someone else can unpack and run.
#
#   powershell -ExecutionPolicy Bypass -File .\package-for-sharing.ps1
#
# What it leaves out and why:
#   node_modules, build, .dart_tool, bin   regenerated by npm/flutter/go, ~2.7 GB of the
#                                          2.7 GB total, so the zip ends up a few MB
#   backend\.env, web\.env                 real secrets (JWT signing key, database
#                                          password, admin password). The .env.example
#                                          files travel instead; SETUP.md says what to put
#                                          in them. Pass -IncludeSecrets to override, only
#                                          ever for your own backup.
#
# It also dumps the database, because the schema is created by the migrations but the
# demo students, marks, skills and drives are not.

param(
    [string] $OutDir = "$PSScriptRoot\..",
    [switch] $IncludeSecrets,
    [switch] $SkipDatabase
)

$ErrorActionPreference = 'Stop'
$root = $PSScriptRoot
$stamp = Get-Date -Format 'yyyy-MM-dd'
$stage = Join-Path ([System.IO.Path]::GetTempPath()) "skills-analyzer-$stamp"
$zip = Join-Path (Resolve-Path $OutDir) "skills-analyzer-$stamp.zip"

if (Test-Path $stage) { Remove-Item $stage -Recurse -Force }
New-Item -ItemType Directory -Path $stage | Out-Null

# ---------- copy the source ----------

# Matched against the path relative to the project root, so "build" only drops the
# Flutter build folder and not, say, a file called build.gradle.kts.
$skipDirs = @(
    'node_modules', '.git', 'dist', 'bin', 'storage', 'storage_test',
    'build', '.dart_tool', '.gradle', '.idea', '.vscode', 'Pods', 'DerivedData'
)
$skipFiles = @('*.log', '*.tmp', '.DS_Store', '*.apk', '*.aab', '*.exe')
if (-not $IncludeSecrets) { $skipFiles += @('.env') }

Write-Host 'Copying source...' -ForegroundColor Cyan
$copied = 0
Get-ChildItem $root -Recurse -File -Force | ForEach-Object {
    $rel = $_.FullName.Substring($root.Length).TrimStart('\')
    $parts = $rel.Split('\')

    if ($parts | Where-Object { $skipDirs -contains $_ }) { return }
    foreach ($pattern in $skipFiles) { if ($_.Name -like $pattern) { return } }

    $target = Join-Path $stage $rel
    $dir = Split-Path $target -Parent
    if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Path $dir -Force | Out-Null }
    Copy-Item $_.FullName $target
    $copied++
}
Write-Host "  $copied files" -ForegroundColor DarkGray

# ---------- dump the database ----------

if (-not $SkipDatabase) {
    $pgDir = Get-ChildItem 'C:\Program Files\PostgreSQL' -Directory -ErrorAction SilentlyContinue |
             Sort-Object Name -Descending | Select-Object -First 1
    $pgDump = if ($pgDir) { Join-Path $pgDir.FullName 'bin\pg_dump.exe' } else { 'pg_dump' }

    # Read the connection string from the backend's .env rather than hard-coding it.
    $envLine = Get-Content "$root\backend\.env" | Where-Object { $_ -match '^DATABASE_URL=' }
    if ($envLine -match 'postgres://([^:]+):([^@]+)@([^:]+):(\d+)/([^?]+)') {
        $user, $pass, $dbHost, $port, $db = $Matches[1..5]
        Write-Host "Dumping database '$db'..." -ForegroundColor Cyan
        $env:PGPASSWORD = $pass
        & $pgDump -h $dbHost -p $port -U $user -d $db --no-owner --no-privileges `
                  -f (Join-Path $stage 'database.sql')
        Remove-Item Env:\PGPASSWORD
        if ($LASTEXITCODE -eq 0) {
            $mb = (Get-Item (Join-Path $stage 'database.sql')).Length / 1MB
            Write-Host ("  database.sql  {0:N1} MB" -f $mb) -ForegroundColor DarkGray
        } else {
            Write-Warning 'pg_dump failed; the zip will have no data. The receiver can seed instead.'
        }
    } else {
        Write-Warning 'Could not read DATABASE_URL from backend\.env; skipping the dump.'
    }
}

# ---------- zip ----------

Write-Host 'Compressing...' -ForegroundColor Cyan
if (Test-Path $zip) { Remove-Item $zip -Force }

# Windows PowerShell's Compress-Archive writes entry paths with backslashes, which macOS
# and Linux unzip into single files with "\" in the name. tar (shipped with Windows 10
# 1803+) writes the forward slashes the zip format actually specifies, so the archive
# opens correctly wherever it is sent.
if (Get-Command tar -ErrorAction SilentlyContinue) {
    Push-Location $stage
    tar -a -c -f $zip *
    Pop-Location
} else {
    Write-Warning 'tar not found; falling back to Compress-Archive. Unzip on Windows only.'
    Compress-Archive -Path "$stage\*" -DestinationPath $zip -CompressionLevel Optimal
}
Remove-Item $stage -Recurse -Force

$size = (Get-Item $zip).Length / 1MB
Write-Host ''
Write-Host ("Done: $zip  ({0:N1} MB)" -f $size) -ForegroundColor Green
if (-not $IncludeSecrets) {
    Write-Host 'Secrets were left out. The receiver copies .env.example to .env — see SETUP.md.' -ForegroundColor Yellow
}
